create database db_MiniProject_25_03_21use db_MiniProject_25_03_21create table tbl_userprofile(userId int primary key identity(1,1),firstName varchar(50),lastName varchar(50),userName varchar(50),password varchar(50))create table tbl_product(productId int primary key identity(1,1),productName varchar(20),produtImg varchar(max),price money,quantity int)create table tbl_checkCart(itemId varchar(max),cartId varchar(max) ,productId int ,quantity int,price money,productName varchar(20),--product varchar(max),totalPrice money,createdDate date,cartStatus varchar(10),userId int foreign key references tbl_userprofile(userid) )Create table tbl_cart(cartId int primary key identity(1,1),productName varchar(20),produtImg varchar(max),price money,totalPrice money,quantity int,productId int FOREIGN KEY REFERENCES tbl_product(productId),userId int foreign key references tbl_userprofile(userid) )drop table tbl_checkCartdrop table tbl_ordersCreate table tbl_orders(orderId int primary key identity(1,1),--productId int FOREIGN KEY REFERENCES tbl_product(productId),--cartId int FOREIGN KEY REFERENCES tbl_cart(cartId),userId int foreign key references tbl_Userprofile(userId),cartDetails varchar(max),--productName varchar(20),--productImg varchar(max),--totalprice money,--quantity int,orderedStatus varchar(10),orderedPrice money,orderedDate date)select count(productname) as counts from tbl_cartselect sum(Price) as subtotal from tbl_cartALTER TABLE tbl_orders
DROP COLUMN cartId;select * from tbl_checkCartselect * from tbl_userprofileselect * from tbl_ordersdelete tbl_checkCart where itemId = 'FD69ED63-909D-429D-A70B-D22B8FE23553'SET IDENTITY_INSERT [dbo].[tbl_product] ON 

INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (1, N'Product 1', 1200.0000, N'assets/Pictures/1.jpg', 50)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (2, N'Product 2', 600.0000, N'assets/Pictures/2.jpg', 40)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (3, N'Product 3', 400.0000, N'assets/Pictures/3.jpg', 10)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (4, N'Product 4', 100.0000, N'assets/Pictures/4.jpg', 5)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (5, N'Product 5', 50.0000, N'assets/Pictures/5.jpg', 50)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (6, N'Product 6', 120.0000, N'assets/Pictures/6.jpg', 10)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (7, N'Product 7', 320.0000, N'assets/Pictures/7.jpg', 20)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (8, N'Product 8', 900.0000, N'assets/Pictures/8.jpg', 30)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (9, N'Product 9', 800.0000, N'assets/Pictures/9.jpg', 36)
INSERT [dbo].[tbl_product] ([productId], [productName], [price], [produtImg], [quantity]) VALUES (10, N'Product 10', 400.0000, N'assets/Pictures/5.jpg', 22)
SET IDENTITY_INSERT [dbo].[tbl_product] OFF